### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by softshape** [surpr1ze/python-sxgeo#5]
Только что подключили sxgeo на продакшен-сервер. Спустя 30 минут сервер начал отваливаться с ошибкой "Too many open files". Отключили sxgeo - перестал отваливаться.

Собственно, вот.

**Comment by surpr1ze** [comment]
А как именно вы его подключили?

**Comment by softshape** [comment]
В миддлварьке -

```
from sxgeo import SxAPI

class GeoApiMiddleware(object):
  def process_request(self, request):
    .....
    user_ip = request.META['REMOTE_ADDR']
    geoapi_db_path = GEOAPI_DB_PATH + '/SxGeoCity.dat'
    api = SxAPI(geoapi_db_path)
    location = api.locate(user_ip)
    if location:
      ...
```

**Comment by surpr1ze** [comment]
Зачем вы каждый раз делаете инициализацию SxAPI? сделайте это 1 раз в **init** и пользуйтесь одним инстансом. В вашем коде на 1 запрос каждый раз происходит открытие нового файла, лимит быстро исчерпывается
